spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-service
      enable-auto-commit: true

  data:
    mongodb:
      host: localhost
      database: order-service
server:
  port: 18080
